import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { X, Bot, Sparkles, Send, CheckCircle } from 'lucide-react';
import { apiCall } from '../../lib/api';

interface AIGradingModalProps {
  isOpen: boolean;
  onClose: () => void;
  assignment: any;
  onSuccess: () => void;
}

export function AIGradingModal({ isOpen, onClose, assignment, onSuccess }: AIGradingModalProps) {
  const [content, setContent] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [result, setResult] = useState<any>(null);

  if (!isOpen || !assignment) return null;

  const handleSubmit = async () => {
    if (!content.trim()) return;
    setIsSubmitting(true);
    try {
      const response = await apiCall(`/courses/assignments/${assignment._id}/ai-grade`, {
        method: 'POST',
        body: JSON.stringify({ content }),
      });
      setResult(response);
      onSuccess();
    } catch (e) {
      console.error(e);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm">
        <motion.div
          initial={{ opacity: 0, scale: 0.95, y: 20 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 20 }}
          className="w-full max-w-2xl bg-white dark:bg-slate-900 rounded-3xl shadow-2xl border border-slate-200 dark:border-slate-700 overflow-hidden flex flex-col max-h-[90vh]"
        >
          {/* Header */}
          <div className="px-6 py-4 border-b border-slate-100 dark:border-slate-800 flex items-center justify-between bg-gradient-to-r from-indigo-50 dark:from-indigo-900/20 to-white dark:to-slate-900">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-[#5b58ed] to-purple-600 flex items-center justify-center text-white shadow-lg">
                <Bot className="w-5 h-5" />
              </div>
              <div>
                <h3 className="text-[15px] font-bold text-slate-900 dark:text-white flex items-center gap-2">
                  Instant AI Grading
                  <Sparkles className="w-4 h-4 text-amber-500" />
                </h3>
                <p className="text-[12px] font-medium text-slate-500">{assignment.title}</p>
              </div>
            </div>
            <button onClick={onClose} className="p-2 text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-full transition-colors">
              <X className="w-5 h-5" />
            </button>
          </div>

          {/* Body */}
          <div className="p-6 overflow-y-auto flex-1">
            {!result ? (
              <div className="space-y-4">
                <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700">
                  <h4 className="text-[13px] font-bold text-slate-900 dark:text-white mb-2">Assignment Details</h4>
                  <p className="text-[13px] text-slate-600 dark:text-slate-400">{assignment.description}</p>
                  <p className="text-[12px] font-bold text-slate-500 mt-3">Max Marks: <span className="text-[#5b58ed]">{assignment.maxMarks}</span></p>
                </div>
                
                <div>
                  <h4 className="text-[13px] font-bold text-slate-900 dark:text-white mb-2">Your Submission</h4>
                  <textarea
                    value={content}
                    onChange={(e) => setContent(e.target.value)}
                    placeholder="Type or paste your assignment answer here..."
                    className="w-full h-40 p-4 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 text-[13px] text-slate-900 dark:text-white placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-[#5b58ed] resize-none"
                  />
                </div>
              </div>
            ) : (
              <div className="space-y-6">
                <div className="flex flex-col items-center text-center p-6 bg-emerald-50 dark:bg-emerald-500/10 border border-emerald-200 dark:border-emerald-500/20 rounded-3xl">
                  <CheckCircle className="w-12 h-12 text-emerald-500 mb-3" />
                  <h3 className="text-2xl font-black text-emerald-600 dark:text-emerald-400 mb-1">
                    {result.marksObtained} / {assignment.maxMarks}
                  </h3>
                  <p className="text-[13px] font-bold text-emerald-800 dark:text-emerald-300">Grade Generated by AI</p>
                </div>

                <div className="p-5 rounded-2xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700">
                  <h4 className="text-[13px] font-bold text-slate-900 dark:text-white mb-3 flex items-center gap-2">
                    <Bot className="w-4 h-4 text-[#5b58ed]" /> Professor AI Feedback
                  </h4>
                  <p className="text-[13px] text-slate-600 dark:text-slate-300 leading-relaxed">
                    {result.feedback}
                  </p>
                </div>
              </div>
            )}
          </div>

          {/* Footer */}
          {!result && (
            <div className="p-4 border-t border-slate-100 dark:border-slate-800 flex justify-end">
              <button
                onClick={handleSubmit}
                disabled={!content.trim() || isSubmitting}
                className="px-6 py-2.5 bg-[#5b58ed] hover:bg-indigo-600 disabled:opacity-50 text-white text-[13px] font-bold rounded-xl shadow-lg shadow-indigo-500/30 flex items-center gap-2 transition-all"
              >
                {isSubmitting ? (
                  <>
                    <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                    Grading...
                  </>
                ) : (
                  <>
                    <Send className="w-4 h-4" />
                    Submit for AI Pre-Grade
                  </>
                )}
              </button>
            </div>
          )}
        </motion.div>
      </div>
    </AnimatePresence>
  );
}
